apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deployment
spec:
  selector:
    matchLabels:
      app: docker-deployment-pod
  template:
    metadata:
      labels:
        app: docker-deployment-pod
    spec:
      containers:
      - name: docker-deployment-container
        image: dssnew.azurecr.io/docker-project:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5295